name: timers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/boop.mp3
    - assets/ending.mp3
    - assets/starting.mp3
  fonts:
    - family: Cousine
      fonts:
        - asset: assets/fonts/Cousine-Regular.ttf
